# Application URL
app-url=http://localhost:4200/#/

# Configuration du serveur
spring.application.name=transi-flex
server.port=8080
server.servlet.context-path=/api
server.max-http-request-header-size=20MB

# Configuration de la base de données
spring.datasource.url=jdbc:postgresql://localhost:5432/transi-flex
spring.datasource.username=postgres
spring.datasource.password=rhd91730660

# Configuration JPA/Hibernate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=none

# Configuration Liquibase
spring.liquibase.change-log=classpath:liquibase/master.xml

# Configuration des uploads
upload.path=${user.home}/transi-flex
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB

# Configuration des logs
logging.level.root=INFO
logging.level.com.transi.flex.account.model.AuthUser=DEBUG
logging.level.com.transi.flex.security.JwtAuthFilter=DEBUG

# Configuration email
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=887724293a448d
spring.mail.password=a400da9d1cec4e
spring.mail.properties.mail.smtp.ssl.enable=false
spring.mail.default-encoding=UTF-8

mail.noreplay.from=noreply@transi-flex.com
mail.noreplay.sender=Transi-Flex No Reply

# Internationalisation
spring.messages.basename=i18n/messages
spring.messages.encoding=UTF-8